### ISSUE TITLE
Helm Chart repository wearefrank is missing index.html

### ISSUE THREAD

**Issue by H3rman8** [wearefrank/charts#14] opened 2024-03-21 13:52 UTC
Unable to add or use the wearefrank helm chart repository due to missing index.html.

# helm repo add wearefrank https://wearefrank.github.io/charts
Error: looks like "https://wearefrank.github.io/charts" is not a valid chart repository or cannot be reached: failed to fetch https://wearefrank.github.io/charts/index.yaml : 404 Not Found

**Comment by philipsens** [comment] 2024-03-22 12:59
That's weird, when I visit the URL I see this:
![image](https://github.com/wearefrank/charts/assets/12416423/2c35e343-6242-4915-9cc4-f718ac3b18d6)

Is your Helm CLI in an air gapped environment? Could you try to run this locally?

**Comment by MLenterman** [comment] 2024-03-22 20:11
This was caused by a failed ci/cd run after a chart version bump. This was confirmed fixed by the reporter yesterday.

**Closed as completed by MLenterman** 2024-03-22 20:11 UTC
